filebeat:
  prospectors:
    - type: log
      enabled: true
      paths:
        - /path/to/****/*.log
      input_type: log
  registry_file: /var/lib/filebeat/registry

output:
  logstash:
    hosts: ["logstash:5044"]
    bulk_max_size: 1024

shipper:

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB

setup.kibana:
  host: "kibana:5601"

filebeat.modules:
- module: nginx
